name: material-of-language
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - cairosvg
  - ipywidgets
  - ffmpeg
  - pip:
    - https://github.com/aparrish/bezmerizing/archive/master.zip
